export let calculatorKeysArray = [{
        inputValue: 'COS',
        id: 'cos',
        buttonColor: 'black'
    }, {
        inputValue: 'TAN',
        id: 'tan',
        buttonColor: 'black'
    }, {
        inputValue: 'SIN',
        id: 'sin',
        buttonColor: 'black'
    }, {
        inputValue: '(-)',
        id: 'plusOrMinus',
        buttonColor: 'black'
    }, {
        inputValue: 'ABS',
        id: 'abs',
        buttonColor: 'black'
    }, {
        inputValue: '√',
        id: 'squareRoot',
        buttonColor: 'black'
    }, {
        inputValue: 'SQR',
        id: 'square',
        buttonColor: 'black'
    }, {
        inputValue: '^',
        id: 'raiseToPower',
        buttonColor: 'black'
    }, {
        inputValue: 'LOG',
        id: 'log',
        buttonColor: 'black'
    }, {
        inputValue: 'ln',
        id: 'ln',
        buttonColor: 'black'
    }, {
        inputValue: 'AC',
        id: 'ac',
        buttonColor: 'black'
    }, {
        inputValue: '(',
        id: 'openParanthesis',
        buttonColor: 'black'
    }, {
        inputValue: ')',
        id: 'closedParanthesis',
        buttonColor: 'black'
    }, {
        inputValue: 'M+',
        id: 'memory',
        buttonColor: 'black'
    }, {
        inputValue: 'MOD',
        id: 'modulus',
        buttonColor: 'black'
    }, {
        inputValue: '7',
        id: '7',
        buttonColor: 'grey'
    }, {
        inputValue: '8',
        id: '8',
        buttonColor: 'grey'
    }, {
        inputValue: '9',
        id: '9',
        buttonColor: 'grey'
    }, {
        inputValue: 'DEL',
        id: 'del',
        buttonColor: 'red'
    }, {
        inputValue: 'EXIT',
        id: 'exit',
        buttonColor: 'red'
    }, {
        inputValue: '4',
        id: '4',
        buttonColor: 'grey'
    }, {
        inputValue: '5',
        id: '5',
        buttonColor: 'grey'
    }, {
        inputValue: '6',
        id: '6',
        buttonColor: 'grey'
    }, {
        inputValue: 'X',
        id: 'multiply',
        buttonColor: 'grey'
    }, {
        inputValue: '/',
        id: 'divide',
        buttonColor: 'grey'
    }, {
        inputValue: '1',
        id: '1',
        buttonColor: 'grey'
    }, {
        inputValue: '2',
        id: '2',
        buttonColor: 'grey'
    }, {
        inputValue: '3',
        id: '3',
        buttonColor: 'grey'
    }, {
        inputValue: '+',
        id: 'add',
        buttonColor: 'grey'
    }, {
        inputValue: '-',
        id: 'subtract',
        buttonColor: 'grey'
    }, {
        inputValue: '0',
        id: '0',
        buttonColor: 'grey'
    }, {
        inputValue: '.',
        id: 'decimal',
        buttonColor: 'grey'
    }, {
        inputValue: 'EXP',
        id: 'exponential',
        buttonColor: 'grey'
    }, {
        inputValue: 'PI',
        id: 'pi',
        buttonColor: 'grey'
    }, {
        inputValue: '=',
        id: 'equalTo',
        buttonColor: 'grey'
    }

];

export let calculatorKeysArrayInverse = [{
        inputValue: 'ACOS',
        id: 'acos',
        buttonColor: 'black'
    }, {
        inputValue: 'ATAN',
        id: 'atan',
        buttonColor: 'black'
    }, {
        inputValue: 'ASIN',
        id: 'asin',
        buttonColor: 'black'
    }, {
        inputValue: '(-)',
        id: 'plusOrMinus',
        buttonColor: 'black'
    }, {
        inputValue: 'ABS',
        id: 'abs',
        buttonColor: 'black'
    }, {
        inputValue: '√',
        id: 'squareRoot',
        buttonColor: 'black'
    }, {
        inputValue: 'SQR',
        id: 'square',
        buttonColor: 'black'
    }, {
        inputValue: '^',
        id: 'raiseToPower',
        buttonColor: 'black'
    }, {
        inputValue: 'LOG',
        id: 'log',
        buttonColor: 'black'
    }, {
        inputValue: 'ln',
        id: 'ln',
        buttonColor: 'black'
    }, {
        inputValue: 'AC',
        id: 'ac',
        buttonColor: 'black'
    }, {
        inputValue: '(',
        id: 'openParanthesis',
        buttonColor: 'black'
    }, {
        inputValue: ')',
        id: 'closedParanthesis',
        buttonColor: 'black'
    }, {
        inputValue: 'M+',
        id: 'memory',
        buttonColor: 'black'
    }, {
        inputValue: 'MOD',
        id: 'modulus',
        buttonColor: 'black'
    }, {
        inputValue: '7',
        id: '7',
        buttonColor: 'grey'
    }, {
        inputValue: '8',
        id: '8',
        buttonColor: 'grey'
    }, {
        inputValue: '9',
        id: '9',
        buttonColor: 'grey'
    }, {
        inputValue: 'DEL',
        id: 'del',
        buttonColor: 'red'
    }, {
        inputValue: 'EXIT',
        id: 'exit',
        buttonColor: 'red'
    }, {
        inputValue: '4',
        id: '4',
        buttonColor: 'grey'
    }, {
        inputValue: '5',
        id: '5',
        buttonColor: 'grey'
    }, {
        inputValue: '6',
        id: '6',
        buttonColor: 'grey'
    }, {
        inputValue: 'X',
        id: 'multiply',
        buttonColor: 'grey'
    }, {
        inputValue: '/',
        id: 'divide',
        buttonColor: 'grey'
    }, {
        inputValue: '1',
        id: '1',
        buttonColor: 'grey'
    }, {
        inputValue: '2',
        id: '2',
        buttonColor: 'grey'
    }, {
        inputValue: '3',
        id: '3',
        buttonColor: 'grey'
    }, {
        inputValue: '+',
        id: 'add',
        buttonColor: 'grey'
    }, {
        inputValue: '-',
        id: 'subtract',
        buttonColor: 'grey'
    }, {
        inputValue: '0',
        id: '0',
        buttonColor: 'grey'
    }, {
        inputValue: '.',
        id: 'decimal',
        buttonColor: 'grey'
    }, {
        inputValue: 'EXP',
        id: 'exponential',
        buttonColor: 'grey'
    }, {
        inputValue: 'PI',
        id: 'pi',
        buttonColor: 'grey'
    }, {
        inputValue: '=',
        id: 'equalTo',
        buttonColor: 'grey'
    }

];

// const calculatorInputButtonsAlt = [...calculatorInputButtons, ]