export let calculatorKeysArray = [{
        btnCharacter: 'COS',
        id: 'cos',
        buttonColor: 'black'
    }, {
        btnCharacter: 'TAN',
        id: 'tan',
        buttonColor: 'black'
    }, {
        btnCharacter: 'SIN',
        id: 'sin',
        buttonColor: 'black'
    }, {
        btnCharacter: '±',
        id: 'plusOrMinus',
        buttonColor: 'black'
    }, {
        btnCharacter: 'ABS',
        id: 'abs',
        buttonColor: 'black'
    }, {
        btnCharacter: '√',
        id: 'squareRoot',
        buttonColor: 'black'
    }, {
        btnCharacter: 'SQR',
        id: 'square',
        buttonColor: 'black'
    }, {
        btnCharacter: '^',
        id: 'raiseToPower',
        buttonColor: 'black'
    }, {
        btnCharacter: 'LOG',
        id: 'log',
        buttonColor: 'black'
    }, {
        btnCharacter: 'In',
        id: 'In',
        buttonColor: 'black'
    }, {
        btnCharacter: 'AC',
        id: 'ac',
        buttonColor: 'black'
    }, {
        btnCharacter: '(',
        id: 'openParanthesis',
        buttonColor: 'black'
    }, {
        btnCharacter: ')',
        id: 'closedParanthesis',
        buttonColor: 'black'
    }, {
        btnCharacter: 'M+',
        id: 'memory',
        buttonColor: 'black'
    }, {
        btnCharacter: 'MOD',
        id: 'modulus',
        buttonColor: 'black'
    }, {
        btnCharacter: '7',
        id: '7',
        buttonColor: 'grey'
    }, {
        btnCharacter: '8',
        id: '8',
        buttonColor: 'grey'
    }, {
        btnCharacter: '9',
        id: '9',
        buttonColor: 'grey'
    }, {
        btnCharacter: 'DEL',
        id: 'del',
        buttonColor: 'red'
    }, {
        btnCharacter: 'EXIT',
        id: 'exit',
        buttonColor: 'red'
    }, {
        btnCharacter: '4',
        id: '4',
        buttonColor: 'grey'
    }, {
        btnCharacter: '5',
        id: '5',
        buttonColor: 'grey'
    }, {
        btnCharacter: '6',
        id: '6',
        buttonColor: 'grey'
    }, {
        btnCharacter: 'X',
        id: 'multiply',
        buttonColor: 'grey'
    }, {
        btnCharacter: '/',
        id: 'divide',
        buttonColor: 'grey'
    }, {
        btnCharacter: '1',
        id: '1',
        buttonColor: 'grey'
    }, {
        btnCharacter: '2',
        id: '2',
        buttonColor: 'grey'
    }, {
        btnCharacter: '3',
        id: '3',
        buttonColor: 'grey'
    }, {
        btnCharacter: '+',
        id: 'add',
        buttonColor: 'grey'
    }, {
        btnCharacter: '-',
        id: 'subtract',
        buttonColor: 'grey'
    }, {
        btnCharacter: '0',
        id: '0',
        buttonColor: 'grey'
    }, {
        btnCharacter: '.',
        id: 'decimal',
        buttonColor: 'grey'
    }, {
        btnCharacter: 'EXP',
        id: 'exponential',
        buttonColor: 'grey'
    }, {
        btnCharacter: 'π',
        id: 'pi',
        buttonColor: 'grey'
    }, {
        btnCharacter: '=',
        id: 'equalTo',
        buttonColor: 'grey'
    }

];

export let calculatorKeysArrayInverse = [{
        btnCharacter: 'ACOS',
        id: 'acos',
        buttonColor: 'black'
    }, {
        btnCharacter: 'ATAN',
        id: 'atan',
        buttonColor: 'black'
    }, {
        btnCharacter: 'ASIN',
        id: 'asin',
        buttonColor: 'black'
    }, {
        btnCharacter: '±',
        id: 'plusOrMinus',
        buttonColor: 'black'
    }, {
        btnCharacter: 'ABS',
        id: 'abs',
        buttonColor: 'black'
    }, {
        btnCharacter: '√',
        id: 'squareRoot',
        buttonColor: 'black'
    }, {
        btnCharacter: 'SQR',
        id: 'square',
        buttonColor: 'black'
    }, {
        btnCharacter: '^',
        id: 'raiseToPower',
        buttonColor: 'black'
    }, {
        btnCharacter: 'LOG',
        id: 'log',
        buttonColor: 'black'
    }, {
        btnCharacter: 'In',
        id: 'In',
        buttonColor: 'black'
    }, {
        btnCharacter: 'AC',
        id: 'ac',
        buttonColor: 'black'
    }, {
        btnCharacter: '(',
        id: 'openParanthesis',
        buttonColor: 'black'
    }, {
        btnCharacter: ')',
        id: 'closedParanthesis',
        buttonColor: 'black'
    }, {
        btnCharacter: 'M+',
        id: 'memory',
        buttonColor: 'black'
    }, {
        btnCharacter: 'MOD',
        id: 'modulus',
        buttonColor: 'black'
    }, {
        btnCharacter: '7',
        id: '7',
        buttonColor: 'grey'
    }, {
        btnCharacter: '8',
        id: '8',
        buttonColor: 'grey'
    }, {
        btnCharacter: '9',
        id: '9',
        buttonColor: 'grey'
    }, {
        btnCharacter: 'DEL',
        id: 'del',
        buttonColor: 'red'
    }, {
        btnCharacter: 'EXIT',
        id: 'exit',
        buttonColor: 'red'
    }, {
        btnCharacter: '4',
        id: '4',
        buttonColor: 'grey'
    }, {
        btnCharacter: '5',
        id: '5',
        buttonColor: 'grey'
    }, {
        btnCharacter: '6',
        id: '6',
        buttonColor: 'grey'
    }, {
        btnCharacter: 'X',
        id: 'multiply',
        buttonColor: 'grey'
    }, {
        btnCharacter: '/',
        id: 'divide',
        buttonColor: 'grey'
    }, {
        btnCharacter: '1',
        id: '1',
        buttonColor: 'grey'
    }, {
        btnCharacter: '2',
        id: '2',
        buttonColor: 'grey'
    }, {
        btnCharacter: '3',
        id: '3',
        buttonColor: 'grey'
    }, {
        btnCharacter: '+',
        id: 'add',
        buttonColor: 'grey'
    }, {
        btnCharacter: '-',
        id: 'subtract',
        buttonColor: 'grey'
    }, {
        btnCharacter: '0',
        id: '0',
        buttonColor: 'grey'
    }, {
        btnCharacter: '.',
        id: 'decimal',
        buttonColor: 'grey'
    }, {
        btnCharacter: 'EXP',
        id: 'exponential',
        buttonColor: 'grey'
    }, {
        btnCharacter: 'π',
        id: 'pi',
        buttonColor: 'grey'
    }, {
        btnCharacter: '=',
        id: 'equalTo',
        buttonColor: 'grey'
    }

];

// const calculatorInputButtonsAlt = [...calculatorInputButtons, ]